name: CI Pipeline - Testing Branch

on:
  push:
    branches: [testing]

jobs:
  test-backend-services:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U postgres -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        service: [customer_service, order_service, product_service]

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies for ${{ matrix.service }}
        run: |
          cd backend/${{ matrix.service }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests for ${{ matrix.service }}
        run: |
          cd backend/${{ matrix.service }}
          python -m pytest tests/ -v

      - name: Run linting for ${{ matrix.service }}
        run: |
          cd backend/${{ matrix.service }}
          pip install flake8
          flake8 app/ --max-line-length=88 --ignore=E203,W503

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-backend-services
    steps:
      - name: Simulate Build and Push
        run: |
          echo "All tests and linting passed successfully."
          echo "Simulating build and push process..."
          echo "Building Docker images..."
          echo "Pushing images to container registry..."
          echo "Build and push simulation complete!"
